# Generated by Django 4.1.6 on 2023-03-05 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_delivery_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_saving',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
