# Generated by Django 4.1.6 on 2023-03-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_client_saving'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('normal', 'Normal'), ('in_office', 'In Office'), ('city', 'City')], default='normal', max_length=20),
        ),
    ]
