# Generated by Django 4.1.6 on 2023-03-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_notes_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('normal', 'Normal'), ('in_office', 'In Office'), ('city', 'City')], default='normal', max_length=20, null=True),
        ),
    ]
