# Generated by Django 4.1.6 on 2023-02-28 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='custody_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='level_badge',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
