# Generated by Django 4.1.6 on 2023-03-01 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delivery_custody_value_delivery_level_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='national_id',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
