# Generated by Django 4.1.6 on 2023-03-04 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_vactaion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vactaion',
            new_name='Vacation',
        ),
    ]
