# Generated by Django 4.1.6 on 2023-03-04 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_vacation_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
