# Generated by Django 4.1.6 on 2023-03-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_vacation_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address_2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
